<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SeventyTwo.Sample.Application\SeventyTwo.Sample.Application.csproj" />
    <ProjectReference Include="..\..\src\SeventyTwo.Sample.Domain\SeventyTwo.Sample.Domain.csproj" />
    <ProjectReference Include="..\..\src\SeventyTwo.Sample.Infrastructure\SeventyTwo.Sample.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\SeventyTwo.Sample.WebApi\SeventyTwo.Sample.WebApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
</Project>
