<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="DotNetCore.CAP" Version="10.0.2" />
    <PackageVersion Include="DotNetCore.CAP.Dashboard" Version="10.0.2" />
    <PackageVersion Include="DotNetCore.CAP.PostgreSql" Version="10.0.2" />
    <PackageVersion Include="DotNetCore.CAP.RabbitMQ" Version="10.0.2" />
    <PackageVersion Include="Mapster" Version="10.0.11" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.8.1" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
    <PackageVersion Include="SeventyTwo.InfraKit" Version="10.10.1" />
    <PackageVersion Include="Serilog.AspNetCore" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="SqlSugarCore" Version="5.1.4.216" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>