<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\SeventyTwo.Sample.Common\SeventyTwo.Sample.Common.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="SeventyTwo.Sample.Infrastructure" />
        <InternalsVisibleTo Include="SeventyTwo.Sample.Domain.Tests" />
        <InternalsVisibleTo Include="SeventyTwo.Sample.ArchitectureTests" />
    </ItemGroup>
</Project>
